apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: pods 
  labels: 
    app: nginx-deploy
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: nginx-deploy 
  template: 
    metadata:
      labels:
        app: nginx-deploy
    spec:
      containers:
        - image: nginx:1.14.2
          name: nginx-deploy
          ports:
           - containerPort: 80